name: deploy

on:
  push:
    branches:
    - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 18
      - run: yarn install
      - run: yarn run next build
      - run: yarn run next export
      - name: rsync deployment
        uses: burnett01/rsync-deployments@5.2.1
        with:
          switches: -avzr --delete --rsync-path="sudo rsync"
          path: out/
          remote_path: ${{ secrets.DEPLOY_PATH }}
          remote_host: ${{ secrets.DEPLOY_HOST }}
          remote_port: 22
          remote_user: ubuntu
          remote_key: ${{ secrets.DEPLOY_KEY }}