name: deploy

on:
  push:
    branches:
    - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: 18
      - run: |
          yarn install
      - name: deploy-sanity
        run: |
          set -e
          cat << EOF > .env.production
          SANITY_STUDIO_FRONTEND_PREVIEW_SECRET=${{ secrets.SANITY_STUDIO_FRONTEND_PREVIEW_SECRET }}
          SANITY_STUDIO_FRONTEND_BASE_URL=${{ secrets.SANITY_STUDIO_FRONTEND_BASE_URL }}
          EOF
      - name: build-next
        run: |
          yarn run next build
          yarn run next export
      - name: deploy-rsync
        uses: burnett01/rsync-deployments@5.2.1
        with:
          switches: -avzr --delete --rsync-path="sudo rsync"
          path: out/
          remote_path: ${{ secrets.DEPLOY_PATH }}
          remote_host: ${{ secrets.DEPLOY_HOST }}
          remote_port: 22
          remote_user: ubuntu
          remote_key: ${{ secrets.DEPLOY_KEY }}